import 'package:flutter/material.dart';

ColorScheme currentColorScheme = lightColorScheme;

ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Colors.white,
  onPrimary: Colors.black,
  primaryContainer: Colors.grey.shade400,
  onPrimaryContainer: Colors.grey.shade800,
  secondary: const Color.fromARGB(255, 33, 116, 36),
  onSecondary: Colors.white,
  secondaryContainer: const Color.fromARGB(255, 75, 145, 78),
  onSecondaryContainer: const Color.fromARGB(255, 24, 87, 26),
  tertiary: const Color.fromARGB(255, 26, 88, 139),
  onTertiary: Colors.white,
  tertiaryContainer: const Color.fromARGB(255, 70, 119, 158),
  onTertiaryContainer: const Color.fromARGB(255, 17, 58, 92),
  error: Colors.red.shade700,
  onError: Colors.white,
  errorContainer: Colors.redAccent,
  onErrorContainer: Colors.red.shade900,
  background: Colors.white,
  onBackground: Colors.grey.shade900,
  surface: Colors.white,
  onSurface: Colors.grey.shade900,
  surfaceVariant: Colors.grey.shade700,
  onSurfaceVariant: Colors.grey.shade800,
  shadow: Colors.black.withOpacity(0.2),
  scrim: Colors.grey.withOpacity(0.1),
);

ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Colors.black,
  onPrimary: Colors.white,
  primaryContainer: Colors.grey.shade800,
  onPrimaryContainer: Colors.white,
  secondary: Colors.green,
  onSecondary: Colors.red,
  secondaryContainer: Colors.red,
  onSecondaryContainer: Colors.cyanAccent,
  tertiary: Colors.lime,
  onTertiary: Colors.deepPurple,
  tertiaryContainer: Colors.green,
  onTertiaryContainer: Colors.tealAccent,
  error: Colors.red.shade900,
  onError: Colors.yellow.shade500,
  errorContainer: Colors.redAccent,
  onErrorContainer: Colors.yellow.shade500,
  background: Colors.grey.shade900,
  onBackground: Colors.white,
  surface: Colors.grey.shade900,
  onSurface: Colors.white,
  surfaceVariant: Colors.grey.shade500,
  onSurfaceVariant: Colors.grey.shade800,
  shadow: Colors.black.withOpacity(0.2),
  scrim: Colors.grey.withOpacity(0.1),
);
